### ISSUE TITLE
setup auto releasing with either semantic-release or intuit auto

### ISSUE THREAD

**Issue by Aghassi** [intuit/standardly#26]
https://github.com/semantic-release/semantic-release

https://github.com/intuit/auto

Don't leave this up to your team. Just have something do it in a standard fashion for you. It will generate all the Changelog things and release tags automatically.

**Comment by hipstersmoothie** [comment]
@jlu17 Okay it’s all set up!

I went ahead and made your CI setup a little more robust and filed a few issues too
